name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BB997951C9D44559A16FD67445497B76 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_669C3423D5E34627A8ABA768AD2C6629 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_46BD3DF9E334466AA2B57BDB6564581F }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vingochiep-2123110365'
          slot-name: 'Production'
          package: .
